# fields (identical for gtfsFeeds and netexFeeds):
# countryIso (required) - ISO 3166-1 alpha-2 country code, e.g. "fr", "de", …
# license (optional) - license abbreviation, e.g. "CC0", "CC-BY 4.0", …
# attribution (required) - name of the data provider (should be used as attribution for licenses that require it, e.g. CC-BY)
# feedUrl (required) - gtfs file url
# infoUrl (required) - url that provides additional information about the feed, usually the website "feedUrl" was taken from
# comments (optional) - additional comments, e.g. regarding the coverage of a feed ("only covers ~95% of all transport")

[[gtfsFeeds]]
  countryIso = "de"
  license = "CC-BY 4.0"
  attribution = "DELFI/opendata-oepnv.de"
  feedUrl = "https://de.data.public-transport.earth/gtfs-germany.zip"
  infoUrl = "https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten-gtfs&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View"

[[gtfsFeeds]]
  countryIso = "lt"
  attribution = "visimarsrutai.lt"
  feedUrl = "https://www.visimarsrutai.lt/gtfs/gtfs_all.zip"
  infoUrl = "https://www.visimarsrutai.lt/gtfs/"

[[netexFeeds]]
  countryIso = "de"
  license = "CC-BY 4.0"
  attribution = "DELFI/opendata-oepnv.de"
  feedUrl = "https://de.data.public-transport.earth/netex-germany.zip"
  infoUrl = "https://www.opendata-oepnv.de/ht/de/organisation/delfi/startseite?tx_vrrkit_view%5Bdataset_name%5D=deutschlandweite-sollfahrplandaten&tx_vrrkit_view%5Bdataset_formats%5D%5B0%5D=ZIP&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View"
