[package]
name = "generate"
version = "0.1.0"
authors = ["Julius Tens <mail@juliustens.eu>"]
edition = "2018"
license = "ISC"

[dependencies]
comrak = "0.10.0"
country-emoji = "0.1.2"
mustache = "0.9.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
