name: CI
on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Test (build)
      uses: docker/build-push-action@v3
      with:
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Fetch commit hash
      id: hash
      run: echo "::set-output name=hash::$(echo $GITHUB_SHA | head -c7)"
    - name: Fetch current date and time
      id: datetime
      run: echo "::set-output name=datetime::$(date -u +'%Y-%m-%dT%H.%M.%SZ')"
    - name: Build and push website container
      uses: docker/build-push-action@v3
      with:
        target: website
        push: true
        tags: ghcr.io/${{github.repository}}-website:v1_${{steps.hash.outputs.hash}}_${{steps.datetime.outputs.datetime}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build and push data container
      uses: docker/build-push-action@v3
      with:
        target: data
        push: true
        tags: ghcr.io/${{github.repository}}-data:v1_${{steps.hash.outputs.hash}}_${{steps.datetime.outputs.datetime}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
