name: Build and deploy
on:
  pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2

    - name: Build container image
      run: docker build .
